{% set name = "visions" %}
{% set version = "0.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eef9a0cdfc0facb753e54ac1cc0af4af8e3ad5d21541aa17e15a405eea252b85

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=19.3.0
    - networkx >=2.4
    - numpy 
    - pandas >=0.25.3
    - python >=3.6
    - tangled-up-in-unicode >=0.0.3

test:
  imports:
    - visions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dylan-profiler/visions
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Visions provides an extensible suite of tools to support common data analysis operations including 
    type inference on unknown data, casting data types and automated data summarization.
  doc_url: https://dylan-profiler.github.io/visions/
  dev_url: https://github.com/dylan-profiler/visions

extra:
  recipe-maintainers:
    - philip-khor
