{% set name = "visions" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00f494a7f78917db2292e11ea832c6e026b64783e688b11da24f4c271ef1631d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True # [py<36]

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python
  run:
    - attrs >=19.3.0
    - networkx >=2.4
    - numpy
    - pandas >=0.25.3
    - python
    - tangled-up-in-unicode >=0.0.4
    - multimethod >=1.4

test:
  imports:
    - visions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dylan-profiler/visions
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Type System for Data Analysis in Python
  description: |
    Visions provides an extensible suite of tools to support common data analysis operations including 
    type inference on unknown data, casting data types and automated data summarization.
  doc_url: https://dylan-profiler.github.io/visions/
  dev_url: https://github.com/dylan-profiler/visions

extra:
  recipe-maintainers:
    - philip-khor
